---
title: "Bayesian_Meta_Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bayesian_Meta_Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gmhs2)
library(ggplot2)
```

```{r}
hyperparameters_ex <- list(#Mu priors N(0,100)
                        "a_mu" = 0,
                        "b_mu" = 100,
                        
                        #Gamma priors N(0,100)
                        "a_gamma" = 0,
                        "b_gamma" = 100,
                        
                        #Tau2 priors 1/Gamma(0.001, 0.001)
                        "a_tau2" = 0.001,
                        "b_tau2" = 0.001)
```

```{r}
data_ex <- read.table(text = "
                  trial rit nit ric nic
                 Balcon 14 56 15 58
                Clausen 18 66 19 64
            Multicentre 15 100 12 95
                 Barber 10 52 12 47
                 Norris 21 226 24 228
                 Kahler 3 38 6 31
                Ledwich 2 20 3 20
                  ", header = TRUE)

data_ex$theta_i <- log(data_ex$rit/data_ex$nit/(1-data_ex$rit/data_ex$nit))-
  log(data_ex$ric/data_ex$nic/(1-data_ex$ric/data_ex$nic))

data_ex$gamma_i <- 0.5*(log(data_ex$rit/data_ex$nit/(1-data_ex$rit/data_ex$nit))+
  log(data_ex$ric/data_ex$nic/(1-data_ex$ric/data_ex$nic)))
```

```{r}
#Rcpp::sourceCpp("../src/rcpparma_marginalLikelihood.cpp")
marginalLikelihood(as.matrix(data_ex[,2:5]), 0.2, 0.1, 10000, 0, 100) 
```
```{r}
optimize_func <- function(Y, mu, tau2){
    optim(par = c("mu" = mu, "tau2" = tau2),
          fn = function(par){
              value <- tryCatch(-marginalLikelihood(Y, par[1], par[2],
                                                100000, 0, 100),
                                error = function(e) Inf)
              if(!is.finite(value)){
                  cat("Non-finite value detected at:", par, "\n")
                  return(0)
              }else{
              return(value)
              }
              },
          method = "L-BFGS-B",
          hessian = FALSE,
          lower = c(0.0001, 0.0001),
          upper = c(0.9, Inf)
          )
}

hats <- optimize_func(Y=as.matrix(data_ex[,2:5]), mu=0.1, tau2=0.1)
```


```{r}
marginalLikelihood(as.matrix(data_ex[,2:5]), 0.2, 0.1, 10000, 0, 100)
marginalLikelihood(as.matrix(data_ex[,2:5]), 0.1443, 0.086, 10000, 0, 100)
```
```{r}
mhGibbs(data_ex, hyperparameters_ex, 0.2, sim = 10, burn = 0)
```
```{r}
posterior_labels <- c('V1' = "Balcon",
                         'V2' = "Clausen",
                         'V3' = "Multicentre",
                         'V4' = "Barber",
                         'V5' = "Norris",
                         'V6' = "Kahler",
                         'V7' = "Ledwich"  )

test <- mhGibbs(data_ex, hyperparameters_ex, 0.01, sim = 1000, burn = 50)$thetas |>
    as.data.frame()

names(test)<- c("Balcon",
                 "Clausen",
                  "Multicentre",
                   "Barber",
                   "Norris",
                   "Kahler",
                   "Ledwich"  )

# test |>
#   tidyr::pivot_longer(everything(),
#                names_to = "Trial",
#                values_to = "Est")|>
#   ggplot2::ggplot()+
#   ggplot2::geom_histogram(aes(x= Est),
#                  binwidth = 0.01)+
#   facet_wrap(~Trial, scales = "free")
```

