# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A "hello world" function
#'
#' A "hello world" function using the Armadillo library.
#'
#' @return
#' A 3x3 matrix with 7 on the diagonal and zero elsewhere.
#' @export
rcpparma_hello_world <- function() {
    .Call('_gmhs2_rcpparma_hello_world', PACKAGE = 'gmhs2')
}

#' Calculates the inner product
#'
#' Calculates the inner product of a vector using the Armadillo library.
#'
#' @param x
#' A numeric vector of length \code{n}.
#' @return
#' The scalar \eqn{x'x}.
#' @export
rcpparma_innerproduct <- function(x) {
    .Call('_gmhs2_rcpparma_innerproduct', PACKAGE = 'gmhs2', x)
}

#' Calculates the outer product
#'
#' Calculates the outer product of a vector using the Armadillo library.
#'
#' @param x
#' A numeric vector x of length \eqn{n}.
#' @return
#' The \eqn{nxn} matrix \eqn{xx'}.
#' @export
rcpparma_outerproduct <- function(x) {
    .Call('_gmhs2_rcpparma_outerproduct', PACKAGE = 'gmhs2', x)
}

#' Calculates both products
#'
#' Calls both the inner and outer product functions, returning a list.
#'
#' @param x
#' A numeric vector of length \eqn{n}.
#' @return
#' A named list with two elements, the scalar inner and the matrix outer.
#' @export
rcpparma_bothproducts <- function(x) {
    .Call('_gmhs2_rcpparma_bothproducts', PACKAGE = 'gmhs2', x)
}

#' Binomial Coefficient
#'
#' Calculates the binomial coefficient
#'
#' @param n
#' Scalar of sample size
#' @param x
#' Scalar of success count
#' @return
#' Coefficient for binomial pmf
#' @export
binomialCoefficient <- function(n, x) {
    .Call('_gmhs2_binomialCoefficient', PACKAGE = 'gmhs2', n, x)
}

#' Binomial Probability Density
#'
#' Alternative to using dbinom
#'
#' @param n
#' Scalar of sample size
#' @param x
#' Scalar of success
#' @param p
#' Scalar probability of success
#' @return
#' Probability density
#' @export
binomialPMF <- function(n, x, p) {
    .Call('_gmhs2_binomialPMF', PACKAGE = 'gmhs2', n, x, p)
}

#' Calculates the marginal likelihood
#'
#' Avoiding numeric integration of thetas and gammas
#'
#' @param Y
#' A numeric matrix with columns for ric, nic, rit, nit
#' @param mu
#' The mean
#' @param tau2
#' The variance
#' @param sim
#' The number of simulations
#' @param a_gamma
#' The mean of prior distribution for gammas
#' @param b_gamma
#' The variance of prior distribution for gammas
#' @return
#' Vector of likelihoods
#' @export
marginalLikelihood <- function(Y, mu, tau2, sim, a_gamma, b_gamma) {
    .Call('_gmhs2_marginalLikelihood', PACKAGE = 'gmhs2', Y, mu, tau2, sim, a_gamma, b_gamma)
}

